# Generated by Django 2.1.5 on 2019-02-01 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0009_auto_20190201_1345'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItensDoPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('desc', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_sales', models.CharField(max_length=7)),
                ('value_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('desc', models.DecimalField(decimal_places=2, max_digits=5)),
                ('taxes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nfe_emitida', models.BooleanField(default=False)),
                ('person_sales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.Person')),
            ],
        ),
        migrations.AddField(
            model_name='itensdopedido',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.Sales'),
        ),
    ]
