# Generated by Django 2.1.5 on 2019-02-04 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_auto_20190201_1655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'permissions': (('setar_nfe', 'Usuário pode alterar parametro NF-e'), ('permissao2', 'Permissao2'), ('permissao3', 'Permissao3'))},
        ),
    ]
