# Generated by Django 2.1.5 on 2019-02-04 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_auto_20190204_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'permissions': (('setar_nfe', 'Usuário pode alterar parametro NF-e'), ('ver_dashboard', 'Usuário pode visualizar Dashborad'), ('permissao3', 'Permissao3'))},
        ),
    ]
