# Generated by Django 2.0 on 2018-12-21 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20181221_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_sales', models.CharField(max_length=7)),
                ('value_sales', models.DecimalField(decimal_places=2, max_digits=5)),
                ('desc', models.DecimalField(decimal_places=2, max_digits=5)),
                ('taxes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('person_sales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.Person')),
            ],
        ),
    ]
