# Generated by Django 2.1.5 on 2019-01-31 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_auto_20181221_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='value_sales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
