# Generated by Django 2.1.5 on 2019-01-31 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_auto_20190131_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='nfe_emitida',
            field=models.BooleanField(default=False),
        ),
    ]
