# Generated by Django 2.1.5 on 2019-02-01 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_sales_nfe_emitida'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItensDoPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('desc', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='sales',
            name='products',
        ),
        migrations.AddField(
            model_name='itensdopedido',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Sales'),
        ),
    ]
