# Generated by Django 2.1.5 on 2019-02-01 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_auto_20190131_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itensdopedido',
            name='product',
        ),
        migrations.RemoveField(
            model_name='itensdopedido',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='person_sales',
        ),
        migrations.DeleteModel(
            name='ItensDoPedido',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
