# Generated by Django 2.1.5 on 2019-02-05 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_auto_20190201_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('deletar_clientes', 'Deletar Clientes'),)},
        ),
    ]
